name: 发布包到 Maven 仓库

on:
  push:
    tags:
      - 'v*'  # 匹配以 'v' 开头的标签

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh  # 这是 Maven 配置中的 <id>
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Install GPG
        run: sudo apt-get update && sudo apt-get install -y gnupg2

      - name: Import GPG key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Trust GPG key
        run: |
          KEY_ID=$(gpg --list-keys --with-colons | grep '^pub' | cut -d':' -f5)
          echo -e "trust\n5\ny\nquit" | gpg --command-fd 0 --batch --edit-key $KEY_ID

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.OSSRH_USERNAME }}</username>
                <password>${{ secrets.OSSRH_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Publish package
        run: |
          mvn --batch-mode clean deploy \
            -Dgpg.executable=gpg \
            -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" \
            -DskipTests
        env:
          GPG_TTY: $(tty)